version: "2"

services:
    app:
        build: .
        command: ["python","main.py","--log","debug"]
        privileged: true
        volumes:
            - ./config:/app/config
        environment:
            - DCSM_CONFIG=/app/config/mfm_power_monitoring_single_phase.toml
